//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from TweetyLang.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="TweetyLangParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface ITweetyLangVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="TweetyLangParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] TweetyLangParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TweetyLangParser.top_level_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTop_level_declaration([NotNull] TweetyLangParser.Top_level_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TweetyLangParser.module_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModule_definition([NotNull] TweetyLangParser.Module_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TweetyLangParser.module_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModule_name([NotNull] TweetyLangParser.Module_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TweetyLangParser.module_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModule_body([NotNull] TweetyLangParser.Module_bodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TweetyLangParser.import_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImport_statement([NotNull] TweetyLangParser.Import_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TweetyLangParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier([NotNull] TweetyLangParser.IdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TweetyLangParser.function_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_definition([NotNull] TweetyLangParser.Function_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TweetyLangParser.function_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_call([NotNull] TweetyLangParser.Function_callContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TweetyLangParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArguments([NotNull] TweetyLangParser.ArgumentsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TweetyLangParser.statement_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement_block([NotNull] TweetyLangParser.Statement_blockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TweetyLangParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] TweetyLangParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TweetyLangParser.raw_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRaw_statement([NotNull] TweetyLangParser.Raw_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TweetyLangParser.compound_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompound_statement([NotNull] TweetyLangParser.Compound_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TweetyLangParser.if_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf_statement([NotNull] TweetyLangParser.If_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TweetyLangParser.else_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElse_block([NotNull] TweetyLangParser.Else_blockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TweetyLangParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment([NotNull] TweetyLangParser.AssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TweetyLangParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaration([NotNull] TweetyLangParser.DeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TweetyLangParser.return_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturn_statement([NotNull] TweetyLangParser.Return_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TweetyLangParser.expression_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression_statement([NotNull] TweetyLangParser.Expression_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TweetyLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] TweetyLangParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TweetyLangParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm([NotNull] TweetyLangParser.TermContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TweetyLangParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFactor([NotNull] TweetyLangParser.FactorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TweetyLangParser.boolean_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolean_literal([NotNull] TweetyLangParser.Boolean_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TweetyLangParser.parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameters([NotNull] TweetyLangParser.ParametersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TweetyLangParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter([NotNull] TweetyLangParser.ParameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TweetyLangParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] TweetyLangParser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TweetyLangParser.pointer_suffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPointer_suffix([NotNull] TweetyLangParser.Pointer_suffixContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TweetyLangParser.raw_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRaw_type([NotNull] TweetyLangParser.Raw_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TweetyLangParser.modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModifier([NotNull] TweetyLangParser.ModifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="TweetyLangParser.char_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitChar_literal([NotNull] TweetyLangParser.Char_literalContext context);
}
