//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from TweetyLang.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="TweetyLangParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface ITweetyLangListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] TweetyLangParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] TweetyLangParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.top_level_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTop_level_declaration([NotNull] TweetyLangParser.Top_level_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.top_level_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTop_level_declaration([NotNull] TweetyLangParser.Top_level_declarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.module_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModule_definition([NotNull] TweetyLangParser.Module_definitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.module_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModule_definition([NotNull] TweetyLangParser.Module_definitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.module_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModule_name([NotNull] TweetyLangParser.Module_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.module_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModule_name([NotNull] TweetyLangParser.Module_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.module_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModule_body([NotNull] TweetyLangParser.Module_bodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.module_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModule_body([NotNull] TweetyLangParser.Module_bodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.import_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImport_statement([NotNull] TweetyLangParser.Import_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.import_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImport_statement([NotNull] TweetyLangParser.Import_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifier([NotNull] TweetyLangParser.IdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifier([NotNull] TweetyLangParser.IdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.function_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_definition([NotNull] TweetyLangParser.Function_definitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.function_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_definition([NotNull] TweetyLangParser.Function_definitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.function_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_body([NotNull] TweetyLangParser.Function_bodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.function_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_body([NotNull] TweetyLangParser.Function_bodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.function_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_call([NotNull] TweetyLangParser.Function_callContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.function_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_call([NotNull] TweetyLangParser.Function_callContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArguments([NotNull] TweetyLangParser.ArgumentsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArguments([NotNull] TweetyLangParser.ArgumentsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] TweetyLangParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] TweetyLangParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.raw_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRaw_statement([NotNull] TweetyLangParser.Raw_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.raw_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRaw_statement([NotNull] TweetyLangParser.Raw_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment([NotNull] TweetyLangParser.AssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment([NotNull] TweetyLangParser.AssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaration([NotNull] TweetyLangParser.DeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaration([NotNull] TweetyLangParser.DeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.return_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturn_statement([NotNull] TweetyLangParser.Return_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.return_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturn_statement([NotNull] TweetyLangParser.Return_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.expression_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression_statement([NotNull] TweetyLangParser.Expression_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.expression_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression_statement([NotNull] TweetyLangParser.Expression_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] TweetyLangParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] TweetyLangParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTerm([NotNull] TweetyLangParser.TermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTerm([NotNull] TweetyLangParser.TermContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFactor([NotNull] TweetyLangParser.FactorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFactor([NotNull] TweetyLangParser.FactorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.boolean_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolean_literal([NotNull] TweetyLangParser.Boolean_literalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.boolean_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolean_literal([NotNull] TweetyLangParser.Boolean_literalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameters([NotNull] TweetyLangParser.ParametersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameters([NotNull] TweetyLangParser.ParametersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameter([NotNull] TweetyLangParser.ParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameter([NotNull] TweetyLangParser.ParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] TweetyLangParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] TweetyLangParser.TypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.pointer_suffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPointer_suffix([NotNull] TweetyLangParser.Pointer_suffixContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.pointer_suffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPointer_suffix([NotNull] TweetyLangParser.Pointer_suffixContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.raw_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRaw_type([NotNull] TweetyLangParser.Raw_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.raw_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRaw_type([NotNull] TweetyLangParser.Raw_typeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.access_modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAccess_modifier([NotNull] TweetyLangParser.Access_modifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.access_modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAccess_modifier([NotNull] TweetyLangParser.Access_modifierContext context);
}
