//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from TweetyLang.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ITweetyLangListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class TweetyLangBaseListener : ITweetyLangListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] TweetyLangParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] TweetyLangParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.top_level_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTop_level_declaration([NotNull] TweetyLangParser.Top_level_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.top_level_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTop_level_declaration([NotNull] TweetyLangParser.Top_level_declarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.module_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModule_definition([NotNull] TweetyLangParser.Module_definitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.module_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModule_definition([NotNull] TweetyLangParser.Module_definitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.module_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModule_name([NotNull] TweetyLangParser.Module_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.module_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModule_name([NotNull] TweetyLangParser.Module_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.module_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModule_body([NotNull] TweetyLangParser.Module_bodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.module_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModule_body([NotNull] TweetyLangParser.Module_bodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.import_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImport_statement([NotNull] TweetyLangParser.Import_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.import_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImport_statement([NotNull] TweetyLangParser.Import_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifier([NotNull] TweetyLangParser.IdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifier([NotNull] TweetyLangParser.IdentifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.function_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_definition([NotNull] TweetyLangParser.Function_definitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.function_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_definition([NotNull] TweetyLangParser.Function_definitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.function_call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_call([NotNull] TweetyLangParser.Function_callContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.function_call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_call([NotNull] TweetyLangParser.Function_callContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.arguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArguments([NotNull] TweetyLangParser.ArgumentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.arguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArguments([NotNull] TweetyLangParser.ArgumentsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.statement_block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement_block([NotNull] TweetyLangParser.Statement_blockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.statement_block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement_block([NotNull] TweetyLangParser.Statement_blockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] TweetyLangParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] TweetyLangParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.raw_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRaw_statement([NotNull] TweetyLangParser.Raw_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.raw_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRaw_statement([NotNull] TweetyLangParser.Raw_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.compound_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompound_statement([NotNull] TweetyLangParser.Compound_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.compound_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompound_statement([NotNull] TweetyLangParser.Compound_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.if_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIf_statement([NotNull] TweetyLangParser.If_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.if_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIf_statement([NotNull] TweetyLangParser.If_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.else_block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElse_block([NotNull] TweetyLangParser.Else_blockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.else_block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElse_block([NotNull] TweetyLangParser.Else_blockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment([NotNull] TweetyLangParser.AssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment([NotNull] TweetyLangParser.AssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclaration([NotNull] TweetyLangParser.DeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclaration([NotNull] TweetyLangParser.DeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.return_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturn_statement([NotNull] TweetyLangParser.Return_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.return_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturn_statement([NotNull] TweetyLangParser.Return_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.expression_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression_statement([NotNull] TweetyLangParser.Expression_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.expression_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression_statement([NotNull] TweetyLangParser.Expression_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] TweetyLangParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] TweetyLangParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerm([NotNull] TweetyLangParser.TermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerm([NotNull] TweetyLangParser.TermContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFactor([NotNull] TweetyLangParser.FactorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFactor([NotNull] TweetyLangParser.FactorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.boolean_literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoolean_literal([NotNull] TweetyLangParser.Boolean_literalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.boolean_literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoolean_literal([NotNull] TweetyLangParser.Boolean_literalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.parameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameters([NotNull] TweetyLangParser.ParametersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.parameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameters([NotNull] TweetyLangParser.ParametersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameter([NotNull] TweetyLangParser.ParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameter([NotNull] TweetyLangParser.ParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType([NotNull] TweetyLangParser.TypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType([NotNull] TweetyLangParser.TypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.pointer_suffix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPointer_suffix([NotNull] TweetyLangParser.Pointer_suffixContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.pointer_suffix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPointer_suffix([NotNull] TweetyLangParser.Pointer_suffixContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.raw_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRaw_type([NotNull] TweetyLangParser.Raw_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.raw_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRaw_type([NotNull] TweetyLangParser.Raw_typeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TweetyLangParser.modifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModifier([NotNull] TweetyLangParser.ModifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TweetyLangParser.modifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModifier([NotNull] TweetyLangParser.ModifierContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
